import Head from 'next/head'
import dynamic from 'next/dynamic'
import React, {Suspense, useState} from "react"
import Loader from '../components/loader/Loader'


const DynamicContentLoading = dynamic(
  () => import('../components/app/App'),
  // eslint-disable-next-line react/display-name
  { loading: () => <Loader/> } 
)

export default function Home() {

  // const [loading, setLoading] = useState(true)

  return (
    <div>
      <Head>
        <title>Arighna Chakraborty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/* <AnimatePresence>
          {
            loading ? (
              <Loader setLoading={setLoading} />
            ): <div className="overflow-x-hidden"><Title/><Work/><Contact/></div>
          }
        </AnimatePresence> */}
        <DynamicContentLoading />
    </div>
  )
}
