import Head from 'next/head'
import Title from '../components/title/Title'
import React, {useState} from "react"
import { AnimatePresence } from 'framer-motion'
import Loader from '../components/loader/Loader'

export default function Home() {

  const [loading, setLoading] = useState(true)

  return (
    <div>
      <Head>
        <title>Arighna Chakraborty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <AnimatePresence>
          {
            loading ? (
              <Loader setLoading={setLoading} />
            ): <Title/>
          }
        </AnimatePresence>
    </div>
  )
}
