import Head from 'next/head'
import dynamic from 'next/dynamic'
import React, {Suspense, useState} from "react"
import Loader from '../components/loader/Loader'
import App from '../components/app/App'
import { AnimatePresence, AnimateSharedLayout } from 'framer-motion'

export default function Home() {

  const [loading, setLoading] = useState(true)

  return (
    <div>
      <Head>
        <title>Arighna Chakraborty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
        <AnimatePresence>
          {
            loading ? (
              <Loader setLoading={setLoading} />
            ): <App/>
          }
        </AnimatePresence>
    </div>
  )
}
